name = "TropicalSweepContractor"
uuid = "75e086d5-add4-4038-bf8f-a400139f199e"
authors = ["nzy1997"]
version = "1.0.0-DEV"

[deps]
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"

[compat]
OMEinsum = "0.8.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
